### ISSUE TITLE
FLOAT32_VEC4 color is wrong in helide device

### ISSUE THREAD

**Issue by UX3D-haertl** [KhronosGroup/ANARI-SDK#231] opened 2024-09-05 14:25 UTC
Running `frame_color_channel.json` in cts:

![grafik](https://github.com/user-attachments/assets/115e5ad1-1b44-4a6b-8df1-e72a6c8d9b23)

**Comment by jeffamstutz** [comment] 2024-09-06 01:58
I added support for changing the color channel format in the viewer (https://github.com/KhronosGroup/ANARI-SDK/pull/232) and haven't been able to reproduce this kind of artifact....could you try out the latest viewer and see if you can reproduce it on your side? I'm starting to wonder if there's an issue with the scene itself, but certainly could be anything.

**Comment by UX3D-haertl** [comment] 2024-09-06 10:01
Is there a way to switch between the color channel formats in the UI or how can I change the format?
Maybe there is an issue with the scene, but ospray renders the scene correctly.

**Comment by johguenther** [comment] 2024-09-06 11:14
I can reproduce this with `cts` (yet the tringles are different although using a `seed` for the random number generator, maybe this is not portable?), but not in the `anariViewer` (to change the FB format bring up the context menu with double-right-click).

The artifact looks like an overflow from one channel to the other when the float is >1.0 (may be the case with OSPRay as well, just not as pronounced, because it renders much darker).

Indeed, a clamp is missing here: https://github.com/KhronosGroup/ANARI-SDK/blob/next_release/cts/src/SceneGenerator.cpp#L1055-L1059

**Comment by jeffamstutz** [comment] 2024-09-06 21:57
Turns out it was a bug in how colors were accumulated between volume/surface/background. Should be fixed in #234.

**Closed** 2024-09-06 22:21 UTC
